# Generated by Django 2.1.4 on 2019-01-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_post_pk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_before_edit',
            field=models.BooleanField(default=False, verbose_name='is before edit?'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and Time published'),
        ),
    ]
